trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
steps:
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: "Part-I-Tools/Azure Pipelines/VM"
    commandOptions: "-var 'subscriptionID=$(subscriptionID)' -var 'network_interface\
_id=$(network_interface_id)'"
    backendServiceArm: 'ROMAN-VSE-MPN(1)(7cb1b750-b4d7-482b-b4da-6779a2d8d7d4)'
    backendAzureRmResourceGroupName: 'DEVOPS'
    backendAzureRmStorageAccountName: 'deovops'
    backendAzureRmContainerName: 'devops'
    backendAzureRmKey: 'tf/terraform.tfstate'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: 'Part-I-Tools/Azure Pipelines/VM'
    commandOptions: '-var="subscriptionID=$(subscriptionID)" -var="network_interface\
_id=$(network_interface_id)"'
    environmentServiceNameAzureRM: 'your_subscription_name_and_id'